// features/mvp-factory/types.ts
// Types for the MVP Factory module.
// Takes opportunities marked "→ MVP Factory" in the AI Analyzer and turns each
// into a concrete MVP specification (generated by Claude) that NZT Studio can
// build and sell.

import type { OppLevel } from "@/features/analyzer/types";

export type Complexity = "low" | "medium" | "high";

/** A single delivery phase of the MVP roadmap. */
export interface MvpPhase {
  title: string;
  description: string;
}

/** The full MVP specification stored for an opportunity. */
export interface MvpSpecData {
  id: string;
  opportunityId: string;
  model: string;
  pitch: string;
  problem: string;
  solution: string;
  targetUser: string;
  coreFeatures: string[];
  futureFeatures: string[];
  techStack: string[];
  phases: MvpPhase[];
  timeline: string;
  complexity: Complexity | null;
  htmlMockup: string | null;
  htmlMockupModel: string | null;
  createdAt: string;
  updatedAt: string;
}

/** Raw, parsed shape returned by the Claude call (before persistence). */
export interface MvpSpecOutput {
  pitch: string;
  problem: string;
  solution: string;
  targetUser: string;
  coreFeatures: string[];
  futureFeatures: string[];
  techStack: string[];
  phases: MvpPhase[];
  timeline: string;
  complexity: Complexity | null;
}

/** Context handed to the AI to generate a spec, sourced from the analysis. */
export interface MvpSpecInput {
  businessName: string;
  businessSummary: string;
  /** "Lo que el negocio ya tiene" — señales de marca/presencia detectadas en el análisis. */
  businessAssets: string[];
  /** Investigación en internet sobre el negocio (texto libre, recortado). */
  businessWebFindings: string;
  opportunityTitle: string;
  opportunityDescription: string;
  opportunityDevelopment: string;
  impact: OppLevel | null;
  effort: OppLevel | null;
  /** Identidad visual real del negocio (colores/tipografía/logo), si se ha detectado o configurado. */
  brandIdentity?: BrandIdentityData | null;
}

// ─── Brand identity ─────────────────────────────────────────────────────────

/** Origin of a brand identity: how it was obtained. */
export type BrandIdentitySource = "website" | "logo" | "manual";

/** A single brand color with a semantic role (e.g. "primary", "background"). */
export interface BrandColor {
  role: string;
  hex: string;
  label?: string;
}

/** Real visual identity of a business — colors, typography, logo, brief. */
export interface BrandIdentityData {
  source: BrandIdentitySource;
  sourceUrl: string | null;
  colors: BrandColor[];
  fontHeading: string | null;
  fontBody: string | null;
  styleNotes: string | null;
  /** Base64-encoded image (no data: prefix). */
  logoImage: string | null;
  logoImageMime: string | null;
  /** Base64-encoded reference/brief image (no data: prefix). */
  referenceImage: string | null;
  referenceImageMime: string | null;
  updatedAt: string;
}

/** Input shape for saving/editing a brand identity manually. */
export interface BrandIdentityInput {
  source: BrandIdentitySource;
  sourceUrl?: string | null;
  colors: BrandColor[];
  fontHeading?: string | null;
  fontBody?: string | null;
  styleNotes?: string | null;
  logoImage?: string | null;
  logoImageMime?: string | null;
  referenceImage?: string | null;
  referenceImageMime?: string | null;
  model?: string | null;
}

/** A persisted AI-generated design mockup for an MVP spec. */
export interface StoredMvpImage {
  id: "hero" | "features" | "detail";
  label: string;
  /** Base64-encoded PNG (no data: prefix). */
  b64: string;
}

/** A selected opportunity in the factory inbox, with its spec if generated. */
export interface FactoryOpportunity {
  id: string;
  title: string;
  description: string;
  development: string;
  impact: OppLevel | null;
  effort: OppLevel | null;
  spec: MvpSpecData | null;
  /** Persisted design mockups (empty if none generated yet). */
  images: StoredMvpImage[];
}

/** A business grouping its selected opportunities for the factory inbox. */
export interface FactoryBusiness {
  placeId: string;
  businessName: string;
  summary: string;
  /** Website URL detected by the Rastreador (Google Places), if any. */
  websiteUri: string | null;
  /** Real visual identity for this business, if detected/configured. */
  brandIdentity: BrandIdentityData | null;
  opportunities: FactoryOpportunity[];
}
